export const programList = [
  {
    id: 1,
    checked: false,
    label: "High School",
  },
  {
    id: 2,
    checked: false,
    label: "Ug Diploma Certificate Associate Degree",
  },
  {
    id: 3,
    checked: false,
    label: "UG",
  },
  {
    id: 4,
    checked: false,
    label: "PG Diploma Certificate",
  },
  {
    id: 5,
    checked: false,
    label: "PG",
  },
  {
    id: 6,
    checked: false,
    label: "UG+PG Accelerated Degree",
  },
  {
    id: 7,
    checked: false,
    label: "PhD",
  },
  {
    id: 8,
    checked: false,
    label: "Foundation",
  },
  {
    id: 9,
    checked: false,
    label: "Short Term Programs",
  },
  {
    id: 10,
    checked: false,
    label: "Pathway Programs",
  },
  {
    id: 11,
    checked: false,
    label: "Twinning Programmes (UG)",
  },
  {
    id: 12,
    checked: false,
    label: "Twinning Programmes (PG)",
  },
];

export const courseList =[
  {
"_id": "61c9a2ce4b8ed3a567c9398e",
"university": "jain university",
"title": "bachelor of business administration",
"specialization": "           -",
"campus": "Jc Road Lalbagh Road Ramanagar Gandhi Nagar Jayanagar 9th Block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c9398f",
"university": "jain university",
"title": "bachelor of computer applications",
"specialization": "internet of things",
"campus": "Jc Road Lalbagh Road Ramanagar Gandhi Nagar Jayanagar 9th Block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 science or commerce with maths/statistics/computer science/information practice",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c93990",
"university": "jain university",
"title": "bachelor of computer applications",
"specialization": "cloud technology and information security",
"campus": "Jc Road Lalbagh Road Ramanagar Gandhi Nagar Jayanagar 9th Block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 science or commerce with maths/statistics/computer science/information practice",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c93991",
"university": "jain university",
"title": "bachelor of computer applications",
"specialization": "cloud technology and mobile application",
"campus": "Jc Road Lalbagh Road Ramanagar Gandhi Nagar Jayanagar 9th Block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 science or commerce with maths/statistics/computer science/information practice",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c93992",
"university": "jain university",
"title": "bachelor of computer applications",
"specialization": "electives",
"campus": "Jc Road Lalbagh Road Ramanagar Gandhi Nagar Jayanagar 9th Block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 science or commerce with maths/statistics/computer science/information practice",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c93993",
"university": "jain university",
"title": "bachelor of computer applications",
"specialization": "mobile application and information security",
"campus": "Jc Road Lalbagh Road Ramanagar Gandhi Nagar Jayanagar 9th Block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 science or commerce with maths/statistics/computer science/information practice",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c93994",
"university": "jain university",
"title": "bachelor of computer applications",
"specialization": "cyber security",
"campus": "Jc Road Lalbagh Road Ramanagar Gandhi Nagar Jayanagar 9th Block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 science or commerce with maths/statistics/computer science/information practice",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c93995",
"university": "jain university",
"title": "bachelor of computer applications",
"specialization": "it for healthcare",
"campus": "Jc Road Lalbagh Road Ramanagar Gandhi Nagar Jayanagar 9th Block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 science or commerce with maths/statistics/computer science/information practice",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c93996",
"university": "jain university",
"title": "bachelor of computer applications",
"specialization": "cognitive systems",
"campus": "Jc Road Lalbagh Road Ramanagar Gandhi Nagar Jayanagar 9th Block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 science or commerce with maths/statistics/computer science/information practice",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c93997",
"university": "jain university",
"title": "bachelor of computer applications",
"specialization": "data analytics",
"campus": "Jc Road Lalbagh Road Ramanagar Gandhi Nagar Jayanagar 9th Block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 science or commerce with maths/statistics/computer science/information practice",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c93998",
"university": "jain university",
"title": "bachelor of computer applications",
"specialization": "uix",
"campus": "Jc Road Lalbagh Road Ramanagar Gandhi Nagar Jayanagar 9th Block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 science or commerce with maths/statistics/computer science/information practice",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c93999",
"university": "jain university",
"title": "bachelor of computer applications",
"specialization": "artificial intelligence & process automation",
"campus": "Jc Road Lalbagh Road Ramanagar Gandhi Nagar Jayanagar 9th Block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 science or commerce with maths/statistics/computer science/information practice",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c9399a",
"university": "jain university ",
"title": "bachelor of design",
"specialization": "industrial design",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 / nios board with a minimum of 45% marks",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c9399b",
"university": "jain university ",
"title": "bachelor of design",
"specialization": "communications & media design",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 / nios board with a minimum of 45% marks",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c9399c",
"university": "jain university ",
"title": "bachelor of design",
"specialization": "lifestyle product & accessory design",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 / nios board with a minimum of 45% marks",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c9399d",
"university": "jain university ",
"title": "business management studies",
"specialization": "financial services",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 examination in science or commerce or arts from puc / isc / cbsc�",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c9399e",
"university": "jain university ",
"title": "business management studies",
"specialization": "international business",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 examination in science or commerce or arts from puc / isc / cbsc�",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c9399f",
"university": "jain university ",
"title": "business management studies",
"specialization": "tourism & hospitality management",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 examination in science or commerce or arts from puc / isc / cbsc�",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939a0",
"university": "jain university ",
"title": "business management studies",
"specialization": "international marketing",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 examination in science or commerce or arts from puc / isc / cbsc�",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939a1",
"university": "jain university ",
"title": "business management studies",
"specialization": "healthcare management",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 examination in science or commerce or arts from puc / isc / cbsc�",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939a2",
"university": "jain university ",
"title": "business management studies",
"specialization": "event management & public relations",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 examination in science or commerce or arts from puc / isc / cbsc�",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939a3",
"university": "jain university ",
"title": "business management studies",
"specialization": "sports management",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 examination in science or commerce or arts from puc / isc / cbsc�",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939a4",
"university": "jain university ",
"title": "business management studies",
"specialization": "aviation management",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 examination in science or commerce or arts from puc / isc / cbsc�",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939a5",
"university": "jain university ",
"title": "business management studies",
"specialization": "branding and entrepreneurship",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 examination in science or commerce or arts from puc / isc / cbsc�",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939a6",
"university": "jain university ",
"title": "business management studies",
"specialization": "digital business",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 examination in science or commerce or arts from puc / isc / cbsc�",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939a7",
"university": "jain university ",
"title": "business management studies",
"specialization": "international finance",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 examination in science or commerce or arts from puc / isc / cbsc�",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939a8",
"university": "jain university ",
"title": "business management studies",
"specialization": "strategy and leadership",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 examination in science or commerce or arts from puc / isc / cbsc�",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939a9",
"university": "jain university ",
"title": "bachelor of technology",
"specialization": "computer science and engineering",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 with physics, chemistry, mathematics/ biology as main subjects",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939aa",
"university": "jain university ",
"title": "bachelor of technology",
"specialization": "cloud technology & information security",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 with physics, chemistry, mathematics/ biology as main subjects",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939ab",
"university": "jain university ",
"title": "bachelor of technology",
"specialization": "internet of things",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 with physics, chemistry, mathematics/ biology as main subjects",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939ac",
"university": "jain university ",
"title": "bachelor of technology",
"specialization": "cloud technology & mobile application",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 with physics, chemistry, mathematics/ biology as main subjects",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939ad",
"university": "jain university ",
"title": "bachelor of technology",
"specialization": "artificial intelligence and machine learning",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 with physics, chemistry, mathematics/ biology as main subjects",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939ae",
"university": "jain university ",
"title": "bachelor of technology",
"specialization": "data science",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 with physics, chemistry, mathematics/ biology as main subjects",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939af",
"university": "jain university ",
"title": "bachelor of technology",
"specialization": "3d printing",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 with physics, chemistry, mathematics/ biology as main subjects",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939b0",
"university": "jain university ",
"title": "bachelor of technology",
"specialization": "nanotechnology",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 with physics, chemistry, mathematics/ biology as main subjects",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939b1",
"university": "jain university ",
"title": "bachelor of technology",
"specialization": "civil engineering",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 with physics, chemistry, mathematics/ biology as main subjects",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939b2",
"university": "jain university ",
"title": "bachelor of technology",
"specialization": "aerospace engineering",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 with physics, chemistry, mathematics/ biology as main subjects",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939b3",
"university": "jain university ",
"title": "bachelor of technology",
"specialization": "electrical and electronics engineering",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 with physics, chemistry, mathematics/ biology as main subjects",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939b4",
"university": "jain university ",
"title": "bachelor of technology",
"specialization": "Eelectronics & communication engineering",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 with physics, chemistry, mathematics/ biology as main subjects",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939b5",
"university": "jain university ",
"title": "bachelor of technology",
"specialization": "information science & engineering",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 with physics, chemistry, mathematics/ biology as main subjects",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939b6",
"university": "jain university ",
"title": "bachelor of technology",
"specialization": "mechanical engineering",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 with physics, chemistry, mathematics/ biology as main subjects",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939b7",
"university": "jain university ",
"title": "bachelor of technology",
"specialization": "aeronautical engineering",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 with physics, chemistry, mathematics/ biology as main subjects",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939b8",
"university": "jain university ",
"title": "bachelor of technology",
"specialization": "software engineering",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 with physics, chemistry, mathematics/ biology as main subjects",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939b9",
"university": "jain university ",
"title": "bachelor of technology",
"specialization": "automobile engineering",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 with physics, chemistry, mathematics/ biology as main subjects",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939ba",
"university": "jain university ",
"title": "bachelor of technology",
"specialization": "robotics and automation",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 with physics, chemistry, mathematics/ biology as main subjects",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939bb",
"university": "jain university ",
"title": "bachelor of technology",
"specialization": "cyber security and digital forensics",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 with physics, chemistry, mathematics/ biology as main subjects",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939bc",
"university": "jain university ",
"title": "bachelor of technology",
"specialization": "mechatronics",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 with physics, chemistry, mathematics/ biology as main subjects",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939bd",
"university": "jain university ",
"title": "bachelor of technology",
"specialization": "cellular technology",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 with physics, chemistry, mathematics/ biology as main subjects",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939be",
"university": "jain university ",
"title": "bachelor of technology",
"specialization": "data engineering and informatics",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 with physics, chemistry, mathematics/ biology as main subjects",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939bf",
"university": "jain university ",
"title": "(b.tech) (lateral)",
"specialization": "bachelor of technology",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 (60% in diploma)",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939c0",
"university": "jain university ",
"title": "master of business administration",
"specialization": "logistics and supply chain management",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "(10+2+3) from any recognized university",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939c1",
"university": "jain university ",
"title": "master of business administration",
"specialization": "working professionals",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "(10+2+3) from any recognized university",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939c2",
"university": "jain university ",
"title": "master of business administration",
"specialization": "finance and human resource management",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "(10+2+3) from any recognized university",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939c3",
"university": "jain university ",
"title": "master of business administration",
"specialization": "banking and finance",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "(10+2+3) from any recognized university",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939c4",
"university": "jain university ",
"title": "master of business administration",
"specialization": "operations management and systems",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "(10+2+3) from any recognized university",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939c5",
"university": "jain university ",
"title": "master of business administration",
"specialization": "business analytics",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "(10+2+3) from any recognized university",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939c6",
"university": "jain university ",
"title": "master of business administration",
"specialization": "sports management",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "(10+2+3) from any recognized university",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939c7",
"university": "jain university ",
"title": "master of business administration",
"specialization": "aviation management",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "(10+2+3) from any recognized university",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939c8",
"university": "jain university ",
"title": "master of business administration",
"specialization": "finance",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "(10+2+3) from any recognized university",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939c9",
"university": "jain university ",
"title": "master of business administration",
"specialization": "human resource management",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "(10+2+3) from any recognized university",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939ca",
"university": "jain university ",
"title": "master of business administration",
"specialization": "international finance",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "(10+2+3) from any recognized university",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939cb",
"university": "jain university ",
"title": "master of business administration",
"specialization": "luxury management",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "(10+2+3) from any recognized university",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939cc",
"university": "jain university ",
"title": "master of business administration",
"specialization": "marketing",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "(10+2+3) from any recognized university",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939cd",
"university": "jain university ",
"title": "master of business administration",
"specialization": "entrepreneurship & family business",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "(10+2+3) from any recognized university",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939ce",
"university": "jain university ",
"title": "master of business administration",
"specialization": "marketing and human resource management",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "(10+2+3) from any recognized university",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939cf",
"university": "jain university ",
"title": "master of business administration",
"specialization": "marketing and finance",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "(10+2+3) from any recognized university",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939d0",
"university": "jain university ",
"title": "master of computer application",
"specialization": "information security management services",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "(10+2+3) minimum of 50% marks in the respective bachelor's degree ",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939d1",
"university": "jain university ",
"title": "master of computer application",
"specialization": "storage & cloud technology",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "(10+2+3) minimum of 50% marks in the respective bachelor's degree ",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939d2",
"university": "jain university ",
"title": "master of computer application",
"specialization": "general",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "(10+2+3) minimum of 50% marks in the respective bachelor's degree ",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939d3",
"university": "jain university ",
"title": "master of computer application",
"specialization": "infrastructure management services",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "(10+2+3) minimum of 50% marks in the respective bachelor's degree ",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939d4",
"university": "jain university ",
"title": "master of laws",
"specialization": "master of laws",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "(10+2)minimum 50% marks in senior secondary or equivalent examination (12th)are eligible to apply for the program.",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939d5",
"university": "jain university ",
"title": "masters in technology",
"specialization": "computer science and engineering",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "(10+2+3) 50% marks of all the years/semesters should be secured in the qualifying examination (45% in the qualifying examination in case of SC, ST).",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939d6",
"university": "jain university ",
"title": "masters in technology",
"specialization": "energy and environmental management",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "(10+2+3) 50% marks of all the years/semesters should be secured in the qualifying examination (45% in the qualifying examination in case of SC, ST).",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939d7",
"university": "jain university ",
"title": "masters in technology",
"specialization": "communication systems",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "(10+2+3) 50% marks of all the years/semesters should be secured in the qualifying examination (45% in the qualifying examination in case of SC, ST).",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939d8",
"university": "jain university ",
"title": "masters in technology",
"specialization": "food technology",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "(10+2+3) 50% marks of all the years/semesters should be secured in the qualifying examination (45% in the qualifying examination in case of SC, ST).",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939d9",
"university": "jain university ",
"title": "masters in technology",
"specialization": "data science",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "(10+2+3) 50% marks of all the years/semesters should be secured in the qualifying examination (45% in the qualifying examination in case of SC, ST).",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939da",
"university": "jain university ",
"title": "masters in technology",
"specialization": "structural engineering",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "(10+2+3) 50% marks of all the years/semesters should be secured in the qualifying examination (45% in the qualifying examination in case of SC, ST).",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939db",
"university": "jain university ",
"title": "masters in technology",
"specialization": "Civil Engineering",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "(10+2+3) 50% marks of all the years/semesters should be secured in the qualifying examination (45% in the qualifying examination in case of SC, ST).",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939dc",
"university": "jain university ",
"title": "masters in technology",
"specialization": "embedded systems",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "(10+2+3) 50% marks of all the years/semesters should be secured in the qualifying examination (45% in the qualifying examination in case of SC, ST).",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939dd",
"university": "jain university ",
"title": "masters in technology",
"specialization": "aerodynamics",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "(10+2+3) 50% marks of all the years/semesters should be secured in the qualifying examination (45% in the qualifying examination in case of SC, ST).",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939de",
"university": "jain university ",
"title": "masters in technology",
"specialization": "aerospace Propulsion Technology",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "(10+2+3) 50% marks of all the years/semesters should be secured in the qualifying examination (45% in the qualifying examination in case of SC, ST).",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939df",
"university": "jain university ",
"title": "masters in technology",
"specialization": "avionics",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "(10+2+3) 50% marks of all the years/semesters should be secured in the qualifying examination (45% in the qualifying examination in case of SC, ST).",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939e0",
"university": "jain university ",
"title": "masters in technology",
"specialization": "internet of things",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "(10+2+3) 50% marks of all the years/semesters should be secured in the qualifying examination (45% in the qualifying examination in case of SC, ST).",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939e1",
"university": "jain university ",
"title": "masters in technology",
"specialization": "artificial intelligence",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "(10+2+3) 50% marks of all the years/semesters should be secured in the qualifying examination (45% in the qualifying examination in case of SC, ST).",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939e2",
"university": "jain university ",
"title": "masters in technology",
"specialization": "cyber security",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "(10+2+3) 50% marks of all the years/semesters should be secured in the qualifying examination (45% in the qualifying examination in case of SC, ST).",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939e3",
"university": "jain university ",
"title": "masters in technology",
"specialization": "structures and design",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "(10+2+3) 50% marks of all the years/semesters should be secured in the qualifying examination (45% in the qualifying examination in case of SC, ST).",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939e4",
"university": "jain university ",
"title": "bachelor of arts",
"specialization": "english",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 (12 with science/ commerce/ arts from a recognised board)",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939e5",
"university": "jain university ",
"title": "bachelor of arts",
"specialization": "psychology",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 (12 with science/ commerce/ arts from a recognised board)",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939e6",
"university": "jain university ",
"title": "bachelor of arts",
"specialization": "sociology",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 (12 with science/ commerce/ arts from a recognised board)",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939e7",
"university": "jain university ",
"title": "bachelor of arts",
"specialization": "journalism and mass communication",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 (12 with science/ commerce/ arts from a recognised board)",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939e8",
"university": "jain university ",
"title": "bachelor of arts",
"specialization": "economics",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 (12 with science/ commerce/ arts from a recognised board)",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939e9",
"university": "jain university ",
"title": "bachelor of arts",
"specialization": "liberal education",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 (12 with science/ commerce/ arts from a recognised board)",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939ea",
"university": "jain university ",
"title": " bachelor of arts honours",
"specialization": "photography",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 (Class 12 with science/ commerce/ arts from a recognised board)",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939eb",
"university": "jain university ",
"title": " bachelor of arts honours",
"specialization": "animation",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 (Class 12 with science/ commerce/ arts from a recognised board)",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939ec",
"university": "jain university ",
"title": " bachelor of arts honours",
"specialization": "visual effects",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 (Class 12 with science/ commerce/ arts from a recognised board)",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939ed",
"university": "jain university ",
"title": " bachelor of arts honours",
"specialization": "healthcare tourism & management",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 (Class 12 with science/ commerce/ arts from a recognised board)",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939ee",
"university": "jain university ",
"title": " bachelor of arts honours",
"specialization": " ui & ux",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 (Class 12 with science/ commerce/ arts from a recognised board)",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939ef",
"university": "jain university ",
"title": " bachelor of arts honours",
"specialization": "advertising",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 (Class 12 with science/ commerce/ arts from a recognised board)",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939f0",
"university": "jain university ",
"title": " bachelor of arts honours",
"specialization": "fashion design",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 (Class 12 with science/ commerce/ arts from a recognised board)",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939f1",
"university": "jain university ",
"title": " bachelor of arts honours",
"specialization": "graphic design",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 (Class 12 with science/ commerce/ arts from a recognised board)",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939f2",
"university": "jain university ",
"title": " bachelor of arts honours",
"specialization": "economics",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 (Class 12 with science/ commerce/ arts from a recognised board)",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939f3",
"university": "jain university ",
"title": " bachelor of arts honours",
"specialization": "game development",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 (Class 12 with science/ commerce/ arts from a recognised board)",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939f4",
"university": "jain university ",
"title": " bachelor of arts honours",
"specialization": "film making & digital production",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 (Class 12 with science/ commerce/ arts from a recognised board)",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939f5",
"university": "jain university ",
"title": " bachelor of arts honours",
"specialization": "music",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 (Class 12 with science/ commerce/ arts from a recognised board)",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939f6",
"university": "jain university ",
"title": "bachelor of commerce",
"specialization": "professional",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "entrance test (jet) is a pass in the 10+2 examination in science / commerce / arts from puc / isc / cbse or equivalent board.",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939f7",
"university": "jain university ",
"title": "bachelor of commerce",
"specialization": "general",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "entrance test (jet) is a pass in the 10+2 examination in science / commerce / arts from puc / isc / cbse or equivalent board.",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939f8",
"university": "jain university ",
"title": "bachelor of commerce",
"specialization": "healthcare",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "entrance test (jet) is a pass in the 10+2 examination in science / commerce / arts from puc / isc / cbse or equivalent board.",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939f9",
"university": "jain university ",
"title": "bachelor of commerce honors",
"specialization": "bachelor of commerce",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "pass in the 10+2 examination in Science or Commerce from PUC / ISC / CBSE or an equivalent board",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939fa",
"university": "jain university ",
"title": "bachelor of vocational",
"specialization": "bachelor of vocational studies",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "a pass in Cass 12 or equivalent from a recognised board. basic knowledge of computers is a must",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939fb",
"university": "jain university ",
"title": "master of arts",
"specialization": "game art & design",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": " (10+2+3) aggregate of 50% in bachelor's degree ",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939fc",
"university": "jain university ",
"title": "master of arts",
"specialization": "economics",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": " (10+2+3) aggregate of 50% in bachelor's degree ",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939fd",
"university": "jain university ",
"title": "master of arts",
"specialization": "english",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": " (10+2+3) aggregate of 50% in bachelor's degree ",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939fe",
"university": "jain university ",
"title": "master of arts",
"specialization": "journalism & mass communication",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": " (10+2+3) aggregate of 50% in bachelor's degree ",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c939ff",
"university": "jain university ",
"title": "master of arts",
"specialization": "public governance & administration",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": " (10+2+3) aggregate of 50% in bachelor's degree ",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c93a00",
"university": "jain university ",
"title": "master of commerce",
"specialization": "business studies",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2+3 ( graduate degree from any recognized university with a minimum of 50% aggregate marks) ",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c93a01",
"university": "jain university ",
"title": "master of commerce",
"specialization": "financial analysis",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2+3 ( graduate degree from any recognized university with a minimum of 50% aggregate marks) ",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c93a02",
"university": "jain university ",
"title": "master of commerce",
"specialization": "banking, insurance and financial services",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2+3 ( graduate degree from any recognized university with a minimum of 50% aggregate marks) ",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c93a03",
"university": "jain university ",
"title": "multimedia messaging service",
"specialization": "business analytics",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "(10+2+3) from any recognized university",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c93a04",
"university": "jain university ",
"title": "multimedia messaging service",
"specialization": "healthcare management",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "(10+2+3) from any recognized university",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c93a05",
"university": "jain university ",
"title": "master of science",
"specialization": "animation",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "aggregate of 50% in bachelor's degree equivalent (10+2+3) from a recognized university ",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c93a06",
"university": "jain university ",
"title": "master of science",
"specialization": "biochemistry",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "aggregate of 50% in bachelor's degree equivalent (10+2+3) from a recognized university ",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c93a07",
"university": "jain university ",
"title": "master of science",
"specialization": "biotechnology",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "aggregate of 50% in bachelor's degree equivalent (10+2+3) from a recognized university ",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c93a08",
"university": "jain university ",
"title": "master of science",
"specialization": "chemistry",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "aggregate of 50% in bachelor's degree equivalent (10+2+3) from a recognized university ",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c93a09",
"university": "jain university ",
"title": "master of science",
"specialization": "forensic sciences",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "aggregate of 50% in bachelor's degree equivalent (10+2+3) from a recognized university ",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c93a0a",
"university": "jain university ",
"title": "master of science",
"specialization": "microbiology",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "aggregate of 50% in bachelor's degree equivalent (10+2+3) from a recognized university ",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c93a0b",
"university": "jain university ",
"title": "master of science",
"specialization": "psychology",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "aggregate of 50% in bachelor's degree equivalent (10+2+3) from a recognized university ",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c93a0c",
"university": "jain university ",
"title": "master of science",
"specialization": "information technology",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "aggregate of 50% in bachelor's degree equivalent (10+2+3) from a recognized university ",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c93a0d",
"university": "jain university ",
"title": "master of science",
"specialization": "physics",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "aggregate of 50% in bachelor's degree equivalent (10+2+3) from a recognized university ",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c93a0e",
"university": "jain university ",
"title": "post graduate diploma",
"specialization": "sports psychology",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 +bachelor's degree with a minimum of 50% marks (45% for SC/ST) in aggregate from a UGC recognized university or equivalent",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c93a0f",
"university": "jain university ",
"title": "post graduate diploma",
"specialization": "capital market management",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 +bachelor's degree with a minimum of 50% marks (45% for SC/ST) in aggregate from a UGC recognized university or equivalent",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
},
{
"_id": "61c9a2ce4b8ed3a567c93a10",
"university": "presidency university",
"title": "post graduate diploma",
"specialization": "psychological counseling",
"campus": "jc road, lalbagh road, ramanagar, gandhi nagar, jayanagar9th block  ",
"country": "india",
"program": "ug",
"duration": "3 years ",
"entryrequirement": "10+2 +bachelor's degree with a minimum of 50% marks (45% for SC/ST) in aggregate from a UGC recognized university or equivalent",
"applicationdeadline": "open",
"applicationfee": "1050",
"price": "160000",
"scholarshipavailable": "available",
"scholarshipdetails": "should be an indian citizen",
"applicationmode": "online",
"remarks": "8.0/10academic"
}
]